name: VS Code Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start VS Code server
        run: |
          docker run -d --name code-server \
            -p 8080:8080 \
            -v "$PWD:/home/coder/project" \
            -v "$HOME/.config/code-server:/home/coder/.config/code-server" \
            codercom/code-server:latest

      - name: Show config.yaml
        run: |
          docker exec code-server cat /home/coder/.config/code-server/config.yaml

      - name: Get password from config.yaml
        run: |
          PASSWORD=$(docker exec code-server cat /home/coder/.config/code-server/config.yaml | grep password | awk '{print $2}')
          echo "Password: $PASSWORD"
