name: ksu

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ksu by ${{ github.actor }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 24

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "10G"

      - name: Prepare Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential git bc bison flex libncurses5-dev libssl-dev gcc-aarch64-linux-gnu
      - name: Patch DTC
        run: |
         sed -i 's/-Werror//' scripts/dtc/Makefile
    
      - name: Build Kernel
        run: |
         export PATH=/usr/bin:$PATH
         make ARCH=arm64 defconfig
         make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- DTC_FLAGS="-@" Image -j$(nproc)

      - name: Package Kernel
        run: |
          mkdir -p output
          cp arch/arm64/boot/Image output/

      - name: Upload Kernel
        uses: softprops/action-gh-release@v1
        with:
          files: output/*
          name: Kernel Build
          tag_name: kernel-build-${{ github.run_id }}
